ECHO OFF
vizinhoBat.exe Instancias/v10.txt
vizinhoBat.exe Instancias/v20.txt
vizinhoBat.exe Instancias/v30a.txt
vizinhoBat.exe Instancias/v30b.txt
vizinhoBat.exe Instancias/v30c.txt
vizinhoBat.exe Instancias/v50a.txt
vizinhoBat.exe Instancias/v50b.txt
vizinhoBat.exe Instancias/v100a.txt
vizinhoBat.exe Instancias/v100b.txt
vizinhoBat.exe Instancias/v250a.txt
vizinhoBat.exe Instancias/v250b.txt
vizinhoBat.exe Instancias/v500a.txt
vizinhoBat.exe Instancias/v500b.txt